import Header from '@/components/layout/Header';
import Sidebar from '@/components/layout/Sidebar';
import '@/lib/fontawesome';
import './globals.css';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="h-screen flex-col bg-black">
                <Header />
                <div className="px-1 flex h-full pt-17 gap-1">
                    <Sidebar />
                    {children}
                </div>
            </body>
        </html>
    );
}
